### ISSUE TITLE
Example Question

### ISSUE THREAD

**Issue by YanlinWangWang** [tpeterka/decaf#1]
After installing decaf through spack, I found that many examples under example were not compiled. 
I tried to compile with cmake but encountered many errors
Can you tell me how to compile them? Thank you

**Comment by orcunyildiz** [comment]
Hi,

Can you indicate which examples are missing when installing with Spack? Currently, science examples that require external dependencies (e.g., lammps, tess-dense) are not installed by default. Will be happy to help to install such dependencies if you can provide what you would need.

**Comment by YanlinWangWang** [comment]
Glad to receive your answer
When I use spack to install, the block_data_model and cfd folders in the example folder are not compiled

**Comment by orcunyildiz** [comment]
Those examples are deprecated, and needs to be removed from the examples folder. Did you need them for some specific reason? Usually, the examples at the direct folder is a good start point for getting started with Decaf.

**Comment by YanlinWangWang** [comment]
thank you for your reply 
I tried to create a new project based on the example, but I encountered a bug. I opened an issue to describe my bug

**Comment by orcunyildiz** [comment]
I replied to the other issue you opened, hence, closing this one.
