### ISSUE TITLE
error:undefined reference to `decaf::Decaf::Decaf(int, Workflow&)'

### ISSUE THREAD

**Issue by YanlinWangWang** [tpeterka/decaf#2]
I encountered a problem while building my own project

/usr/bin/ld: warning: libboost_serialization.so.1.74.0, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libbredala_datamodel.so, may conflict with libboost_serialization.so.1.65.1
CMakeFiles/decaftest.dir/main.cpp.o: In function `run(Workflow&)':
/home/razer/Desktop/decaftest/main.cpp:87: undefined reference to `decaf::Decaf::Decaf(int, Workflow&)'
collect2: error: ld returned 1 exit status

I am sure I have introduced the required static link library
And This is my cmake file

cmake_minimum_required(VERSION 3.17)
project(decaftest)
set(CMAKE_CXX_STANDARD 11)

add_executable(decaftest main.cpp)

INCLUDE_DIRECTORIES(/home/razer/Desktop/decaf/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/decaf-master-apws26lvkzilwx53nz6uvi3tegzvn2kl/include)

target_link_libraries(decaftest  libdecaf.so  libbredala_datamodel.so  libbredala_transport_mpi.so libboost_serialization.so.1.65.1)

**Comment by orcunyildiz** [comment]
Maybe instead of creating a new project, you can try to build Decaf manually by following the instructions at the README file. Then, you can create the new examples as you would like, or build upon the existing examples such as the ones in the direct folder.

**Comment by YanlinWangWang** [comment]
According to your prompt, I successfully ran the project, but an error occurred when running the python example.
  File "./con.py", line 1, in <module>
    import pybredala as bd
ModuleNotFoundError: No module named 'pybredala'
Traceback (most recent call last):
  File "./prod.py", line 1, in <module>
    import pybredala as bd
ModuleNotFoundError: No module named 'pybredala'
I can’t find the corresponding file in your project. Can you tell me how to solve it?

**Comment by orcunyildiz** [comment]
pybredala and pydecaf modules are located under ${CMAKE_INSTALL_PREFIX}/examples/python/. 

To run the python test examples, you can do:
$ cd /path/to/Decaf/install/examples/python
$ python3 linear-2nodes.py
$ sh linear2.sh
